# Generated by Django 3.2.6 on 2022-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
