# Generated by Django 3.2.6 on 2022-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0002_auto_20220219_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
