# Generated by Django 3.2.6 on 2022-03-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ClubNetwork.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ClubNetwork.user')),
            ],
        ),
    ]
