# Generated by Django 3.2.6 on 2022-04-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0009_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
