# Generated by Django 3.2.6 on 2022-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0010_club_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
