# Generated by Django 3.2.6 on 2022-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0011_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='is_verified',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not_verified'), (2, 'eligible'), (3, 'requested'), (4, 'verified')], default=1),
        ),
    ]
