# Generated by Django 3.2.6 on 2022-04-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubNetwork', '0012_alter_club_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='is_verified',
            field=models.PositiveSmallIntegerField(choices=[(1, 'not_verified'), (2, 'requested'), (3, 'verified')], default=1),
        ),
    ]
